#!/usr/bin/env python3
"""Aeronaves y satélites del hero de zodk.eu, en pixel art.

Cada nave = un MAPA ASCII (1 carácter = 1 celda) + opcionalmente unos DISCOS
que se dibujan encima (radomos, hélices, platos). Se rasteriza a un SVG por
tema (día / noche), con el estilo del dron original: sombreado de arriba (claro)
a abajo (oscuro), contorno navy de 1 px y, de noche, luces de posición.

    python3 generar-aeronaves.py        # -> ../public/zodk-<id>[-noche].svg

Las dimensiones (viewBox) que imprime al final van a src/data/aeronaves.ts.

Leyenda:
    .  vacío        #  casco claro     o  casco medio     x  casco oscuro
    =  panel claro  -  panel oscuro    d  radomo/disco    c  cristal/óptica
    b  hélice       *  acento (magenta de día, se apaga de noche)
"""
import math
import os

DIA = {
    "#": "#eef2f6", "o": "#c6cfd7", "x": "#8a94a0", "X": "#6c7681",
    "=": "#dde3e8", "-": "#aab3bb", "d": "#e6ebef", "+": "#ffffff",
    "c": "#243449", "b": "#f4f7fa", "*": "#e91e8c",
    "ring": "#0f1c30",
}
NOCHE = {
    "#": "#5e6874", "o": "#4a5560", "x": "#38414d", "X": "#2b333d",
    "=": "#545e6a", "-": "#3e4754", "d": "#616b77", "+": "#7f8a97",
    "c": "#131c28", "b": "#727d8a", "*": "#5e6874",
    "ring": "#050a12",
}

NAV_NOSE, NAV_RIGHT, NAV_LEFT = "#ffd23c", "#33dd66", "#ff3b30"

# --------------------------------------------------------------- definiciones
# Morro / frente SIEMPRE a la izquierda. 1 celda de margen para el contorno.
CRAFT = {}

# Bayraktar TB3 — vista cenital. Morro romo tipo "cabeza de beluga" (uniforme,
# sin bola ni cúpula), fuselaje fino, alas RECTAS finas y largas, hélice
# propulsora, y una cola de dos pértigas finas que se juntan en un triángulo.
CRAFT["tb3"] = dict(dp=4, label="Bayraktar TB3", art="""
..............................................
................==............................
................==............................
................==............................
................==............................
................==............................
................==............................
................==............................
.........########==########.........o.........
.......##################xxo........ooo........
......###################xxoooooooooo=====.....
.......##################xxo........ooo........
.........########==########.........o.........
................==............................
................==............................
................==............................
................==............................
................==............................
................==............................
................==............................
..............................................
""", discs=[(7.0, 10.5, 4.3, "#"), (5.6, 10.5, 2.9, "o"),
             (27, 10.5, 2.2, "b")],
   nav=dict(nose=(2, 10), right=(16, 1), left=(16, 19)))

# E-2 Hawkeye — vista de PERFIL ("avioneta"). Lo que manda: el radomo (disco
# aplanado) montado sobre dos pilones encima del fuselaje trasero. Debajo, un
# bimotor de hélice con ala alta y la cola de cuatro derivas.
CRAFT["e2-hawkeye"] = dict(dp=4, label="E-2 Hawkeye", art="""
..............................................
..................================............
...............======================.........
.............==========================.......
...............======================.........
..................================............
...................o..........o...............
...................o..........o...............
..................o............o..............
..................o............o.......==......
..cc..############o############o####...===.....
.c#################################x..====.....
.c##################################x.=====....
.c#######ooooooooooo################xx.====#...
.c#######ooooooooooo###############xxx.===##...
.c#######ooooooooooo###############xx#.==###...
..######ooooooooooo##############xx###...###...
..bbb###===========#############xx####.........
..bbb##===ooooooo===###########xx#####.........
..bbb###===========###########x#######.........
...####ooooooooooooo#########xx#######.........
....xx#####################xxxx#######.........
..............................................
""", discs=[(22, 3.5, 2.0, "+"), (3.5, 18, 2.3, "b")],
   nav=dict(nose=(2, 12), right=(19, 6), left=(19, 8)))

# Satélite de reconocimiento óptico (genérico "Keyhole") — cuerpo central con
# paneles y estrelleros, dos alas solares grandes (celdas en rejilla) sobre
# yugos, y el telescopio con su plato apuntando a la Tierra (abajo).
CRAFT["sat-recon"] = dict(dp=4, label="Satelite de reconocimiento", art="""
..........................................
...==-==-==-==....o####o....==-==-==-==....
...==-==-==-==....o#XX#o....==-==-==-==....
...==-==-==-==...oo#XX#oo...==-==-==-==....
...==-==-==-==....o#XX#o....==-==-==-==....
...--+--+--+--....X####X....--+--+--+--....
...==-==-==-==...X######X...==-==-==-==....
..===-==-==-==-==X##XX##X==-==-==-==-==-....
..===-==-==-==-==X##XX##X==-==-==-==-==-....
...==-==-==-==...X######X...==-==-==-==....
...--+--+--+--....X####X....--+--+--+--....
...==-==-==-==....o#XX#o....==-==-==-==....
...==-==-==-==....o####o....==-==-==-==....
.................o.XX.o....................
................oo.XX.oo...................
...............ooo.XX.ooo..................
................oo.XX.oo...................
.................ooooo.....................
..................ooo.....................
...................o......................
..........................................
""", discs=[(20.5, 15.5, 4.6, "X"), (20.5, 15.5, 3.2, "o"), (20.5, 15, 1.2, "c")],
   nav=dict(nose=None, right=None, left=None))

# Sentinel-2 (Copernicus / ESA) — colores reales: cuerpo forrado en aislante
# multicapa DORADO (con arrugas: brillos y sombras), y un ala solar larga de
# células AZULES ditheradas (dos tonos alternos + destellos) sobre su yugo.
# Abajo, la óptica del instrumento MSI (negra).
#   Glifos:  # o x  dorado claro/medio/sombra   H brillo dorado
#            = -     célula azul A / B (dither)  | junta rejilla   + destello
#            y       yugo (dorado oscuro)        c óptica / negro
CRAFT["sat-sentinel"] = dict(
    dp=4, label="Sentinel-2",
    pal_d={
        "H": "#f6e2a8", "#": "#d9b060", "o": "#b08a41", "x": "#775824",
        "y": "#5a451e",
        "=": "#41528f", "-": "#1e2850", "+": "#cdd8f2", "|": "#0d1430",
        "c": "#131319", "ring": "#0c1526",
    },
    pal_n={
        "H": "#877655", "#": "#6a5837", "o": "#544629", "x": "#3a3120",
        "y": "#2f2716",
        "=": "#303a66", "-": "#181f3a", "+": "#6b789e", "|": "#0a1020",
        "c": "#0f1016", "ring": "#050a12",
    },
    art="""
..............................................
.....HHH######HHH..............................
....H############H.............................
....#HHHHHHHHHHHH#.............................
....#oooooooooooo#.............................
....#xxxxxxxxxxxx#..-==|--|+=|--|==|--|=+|--|==|-.
....#oooooooooooo#y.-=+|--|==|-+|==|--|==|--|+=|-.
....#HHHHHHHHHHHH#y.-==|-+|==|--|=+|--|+=|--|==|-.
....#oooooooooooo#y.-+=|--|==|--|==|-+|==|--|==|-.
....#xxxxxxxxxxxx#y.-==|--|+=|--|==|--|==|-+|==|-.
....#oooooooooooo#y.-==|-+|==|--|=+|--|==|--|+=|-.
....#HHHHHHHHHHHH#y.-+=|--|==|-+|==|--|+=|--|==|-.
....#oooooooooooo#y.-==|--|==|--|==|--|==|--|==|-.
....H############H.-==|--|+=|--|==|--|=+|--|==|-.
.....xx######xx................................
......#oooo#...................................
......#cccc#...................................
......#cccc#...................................
......occco....................................
.......oooo....................................
.......xoox....................................
..............................................
""",
    discs=[], nav=dict(nose=None, right=None, left=None))


# --------------------------------------------------------------------- render
def _grid(art):
    lines = art.strip("\n").splitlines()
    w = max(len(ln) for ln in lines)
    return [list(ln.ljust(w)) for ln in lines], w, len(lines)


def craft_svg(cid, night):
    spec = CRAFT[cid]
    pal = {**(NOCHE if night else DIA),
           **spec.get("pal_n" if night else "pal_d", {})}
    dp = spec["dp"]
    rows, w, h = _grid(spec["art"])

    for cx, cy, r, ch in spec.get("discs", []):
        for r_ in range(h):
            for c_ in range(w):
                if (c_ - cx) ** 2 + (r_ - cy) ** 2 <= r * r:
                    rows[r_][c_] = ch

    cells = {}
    for r, line in enumerate(rows):
        for c, ch in enumerate(line):
            if ch in pal and ch != "ring":
                cells[(c, r)] = pal[ch]

    if night:
        for key, col in (("nose", NAV_NOSE), ("right", NAV_RIGHT), ("left", NAV_LEFT)):
            p = spec.get("nav", {}).get(key)
            if p and tuple(p) in cells:
                cells[tuple(p)] = col

    ring = {}
    for (c, r) in cells:
        for dc in (-1, 0, 1):
            for dr in (-1, 0, 1):
                if (c + dc, r + dr) not in cells:
                    ring[(c + dc, r + dr)] = pal["ring"]

    vw, vh = (w + 2) * dp, (h + 2) * dp
    rects = "".join(
        f'<rect x="{(c + 1) * dp}" y="{(r + 1) * dp}" width="{dp}" height="{dp}" fill="{col}"/>'
        for (c, r), col in list(ring.items()) + list(cells.items())
    )
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {vw} {vh}" '
            f'width="{vw}" height="{vh}" shape-rendering="crispEdges" '
            f'role="img" aria-label="{spec["label"]}">{rects}</svg>\n'), vw, vh


if __name__ == "__main__":
    out = os.path.join(os.path.dirname(__file__), "..", "public")
    for cid in CRAFT:
        svg_d, vw, vh = craft_svg(cid, False)
        svg_n, _, _ = craft_svg(cid, True)
        open(os.path.join(out, f"zodk-{cid}.svg"), "w").write(svg_d)
        open(os.path.join(out, f"zodk-{cid}-noche.svg"), "w").write(svg_n)
        print(f"{cid:16} {vw:3} x {vh:3}")
